#upset plots control vs case
i=1
mcontrol=make_comb_mat(enginesidentification[[controlcase[i,]$Control]], mode = "intersect")
mcase=make_comb_mat(enginesidentification[[controlcase[i,]$Case]], mode = "intersect")
png(filename = paste0("UpsetsControlVsCase/",controlcase[i,]$Control," vs ",controlcase[i,]$Case,".png"),width = 512,height = 512)
UpSet(mcontrol[comb_degree(mcontrol)>=2], row_title =controlcase[i,]$Control)%v%UpSet(mcase[comb_degree(mcase)>=2], row_title =controlcase[i,]$Case)
dev.off()
i=i+1
mcontrol=make_comb_mat(enginesidentification[[controlcase[i,]$Control]], mode = "intersect")
mcase=make_comb_mat(enginesidentification[[controlcase[i,]$Case]], mode = "intersect")
png(filename = paste0("UpsetsControlVsCase/",controlcase[i,]$Control," vs ",controlcase[i,]$Case,".png"),width = 512,height = 512)
UpSet(mcontrol[comb_degree(mcontrol)>=2], row_title =controlcase[i,]$Control)%v%UpSet(mcase[comb_degree(mcase)>=2], row_title =controlcase[i,]$Case)
dev.off()
i=i+1
mcontrol=make_comb_mat(enginesidentification[[controlcase[i,]$Control]], mode = "intersect")
mcase=make_comb_mat(enginesidentification[[controlcase[i,]$Case]], mode = "intersect")
png(filename = paste0("UpsetsControlVsCase/",controlcase[i,]$Control," vs ",controlcase[i,]$Case,".png"),width = 512,height = 512)
UpSet(mcontrol[comb_degree(mcontrol)>=2], row_title =controlcase[i,]$Control)%v%UpSet(mcase[comb_degree(mcase)>=2], row_title =controlcase[i,]$Case)
dev.off()
i=i+1
mcontrol=make_comb_mat(enginesidentification[[controlcase[i,]$Control]], mode = "intersect")
mcase=make_comb_mat(enginesidentification[[controlcase[i,]$Case]], mode = "intersect")
png(filename = paste0("UpsetsControlVsCase/",controlcase[i,]$Control," vs ",controlcase[i,]$Case,".png"),width = 512,height = 512)
UpSet(mcontrol[comb_degree(mcontrol)>=2], row_title =controlcase[i,]$Control)%v%UpSet(mcase[comb_degree(mcase)>=2], row_title =controlcase[i,]$Case)
dev.off()
i=i+1
mcontrol=make_comb_mat(enginesidentification[[controlcase[i,]$Control]], mode = "intersect")
mcase=make_comb_mat(enginesidentification[[controlcase[i,]$Case]], mode = "intersect")
png(filename = paste0("UpsetsControlVsCase/",controlcase[i,]$Control," vs ",controlcase[i,]$Case,".png"),width = 512,height = 512)
UpSet(mcontrol[comb_degree(mcontrol)>=2], row_title =controlcase[i,]$Control)%v%UpSet(mcase[comb_degree(mcase)>=2], row_title =controlcase[i,]$Case)
dev.off()
i=i+1
mcontrol=make_comb_mat(enginesidentification[[controlcase[i,]$Control]], mode = "intersect")
mcase=make_comb_mat(enginesidentification[[controlcase[i,]$Case]], mode = "intersect")
png(filename = paste0("UpsetsControlVsCase/",controlcase[i,]$Control," vs ",controlcase[i,]$Case,".png"),width = 512,height = 512)
UpSet(mcontrol[comb_degree(mcontrol)>=2], row_title =controlcase[i,]$Control)%v%UpSet(mcase[comb_degree(mcase)>=2], row_title =controlcase[i,]$Case)
dev.off()
i=i+1
mcontrol=make_comb_mat(enginesidentification[[controlcase[i,]$Control]], mode = "intersect")
mcase=make_comb_mat(enginesidentification[[controlcase[i,]$Case]], mode = "intersect")
png(filename = paste0("UpsetsControlVsCase/",controlcase[i,]$Control," vs ",controlcase[i,]$Case,".png"),width = 512,height = 512)
UpSet(mcontrol[comb_degree(mcontrol)>=2], row_title =controlcase[i,]$Control)%v%UpSet(mcase[comb_degree(mcase)>=2], row_title =controlcase[i,]$Case)
dev.off()
i=i+1
mcontrol=make_comb_mat(enginesidentification[[controlcase[i,]$Control]], mode = "intersect")
mcase=make_comb_mat(enginesidentification[[controlcase[i,]$Case]], mode = "intersect")
png(filename = paste0("UpsetsControlVsCase/",controlcase[i,]$Control," vs ",controlcase[i,]$Case,".png"),width = 512,height = 512)
UpSet(mcontrol[comb_degree(mcontrol)>=2], row_title =controlcase[i,]$Control)%v%UpSet(mcase[comb_degree(mcase)>=2], row_title =controlcase[i,]$Case)
dev.off()
i=i+1
mcontrol=make_comb_mat(enginesidentification[[controlcase[i,]$Control]], mode = "intersect")
mcase=make_comb_mat(enginesidentification[[controlcase[i,]$Case]], mode = "intersect")
png(filename = paste0("UpsetsControlVsCase/",controlcase[i,]$Control," vs ",controlcase[i,]$Case,".png"),width = 512,height = 512)
UpSet(mcontrol[comb_degree(mcontrol)>=2], row_title =controlcase[i,]$Control)%v%UpSet(mcase[comb_degree(mcase)>=2], row_title =controlcase[i,]$Case)
dev.off()
i=i+1
mcontrol=make_comb_mat(enginesidentification[[controlcase[i,]$Control]], mode = "intersect")
mcase=make_comb_mat(enginesidentification[[controlcase[i,]$Case]], mode = "intersect")
png(filename = paste0("UpsetsControlVsCase/",controlcase[i,]$Control," vs ",controlcase[i,]$Case,".png"),width = 512,height = 512)
UpSet(mcontrol[comb_degree(mcontrol)>=2], row_title =controlcase[i,]$Control)%v%UpSet(mcase[comb_degree(mcase)>=2], row_title =controlcase[i,]$Case)
dev.off()
i=i+1
mcontrol=make_comb_mat(enginesidentification[[controlcase[i,]$Control]], mode = "intersect")
mcase=make_comb_mat(enginesidentification[[controlcase[i,]$Case]], mode = "intersect")
png(filename = paste0("UpsetsControlVsCase/",controlcase[i,]$Control," vs ",controlcase[i,]$Case,".png"),width = 512,height = 512)
UpSet(mcontrol[comb_degree(mcontrol)>=2], row_title =controlcase[i,]$Control)%v%UpSet(mcase[comb_degree(mcase)>=2], row_title =controlcase[i,]$Case)
dev.off()
i=i+1
mcontrol=make_comb_mat(enginesidentification[[controlcase[i,]$Control]], mode = "intersect")
mcase=make_comb_mat(enginesidentification[[controlcase[i,]$Case]], mode = "intersect")
png(filename = paste0("UpsetsControlVsCase/",controlcase[i,]$Control," vs ",controlcase[i,]$Case,".png"),width = 512,height = 512)
UpSet(mcontrol[comb_degree(mcontrol)>=2], row_title =controlcase[i,]$Control)%v%UpSet(mcase[comb_degree(mcase)>=2], row_title =controlcase[i,]$Case)
dev.off()
i=i+1
mcontrol=make_comb_mat(enginesidentification[[controlcase[i,]$Control]], mode = "intersect")
mcase=make_comb_mat(enginesidentification[[controlcase[i,]$Case]], mode = "intersect")
png(filename = paste0("UpsetsControlVsCase/",controlcase[i,]$Control," vs ",controlcase[i,]$Case,".png"),width = 512,height = 512)
UpSet(mcontrol[comb_degree(mcontrol)>=2], row_title =controlcase[i,]$Control)%v%UpSet(mcase[comb_degree(mcase)>=2], row_title =controlcase[i,]$Case)
dev.off()
i=i+1
mcontrol=make_comb_mat(enginesidentification[[controlcase[i,]$Control]], mode = "intersect")
mcase=make_comb_mat(enginesidentification[[controlcase[i,]$Case]], mode = "intersect")
png(filename = paste0("UpsetsControlVsCase/",controlcase[i,]$Control," vs ",controlcase[i,]$Case,".png"),width = 512,height = 512)
UpSet(mcontrol[comb_degree(mcontrol)>=2], row_title =controlcase[i,]$Control)%v%UpSet(mcase[comb_degree(mcase)>=2], row_title =controlcase[i,]$Case)
dev.off()
i=i+1
mcontrol=make_comb_mat(enginesidentification[[controlcase[i,]$Control]], mode = "intersect")
mcase=make_comb_mat(enginesidentification[[controlcase[i,]$Case]], mode = "intersect")
png(filename = paste0("UpsetsControlVsCase/",controlcase[i,]$Control," vs ",controlcase[i,]$Case,".png"),width = 512,height = 512)
UpSet(mcontrol[comb_degree(mcontrol)>=2], row_title =controlcase[i,]$Control)%v%UpSet(mcase[comb_degree(mcase)>=2], row_title =controlcase[i,]$Case)
dev.off()
i=i+1
mcontrol=make_comb_mat(enginesidentification[[controlcase[i,]$Control]], mode = "intersect")
mcase=make_comb_mat(enginesidentification[[controlcase[i,]$Case]], mode = "intersect")
png(filename = paste0("UpsetsControlVsCase/",controlcase[i,]$Control," vs ",controlcase[i,]$Case,".png"),width = 512,height = 512)
UpSet(mcontrol[comb_degree(mcontrol)>=2], row_title =controlcase[i,]$Control)%v%UpSet(mcase[comb_degree(mcase)>=2], row_title =controlcase[i,]$Case)
dev.off()
i=i+1
mcontrol=make_comb_mat(enginesidentification[[controlcase[i,]$Control]], mode = "intersect")
mcase=make_comb_mat(enginesidentification[[controlcase[i,]$Case]], mode = "intersect")
png(filename = paste0("UpsetsControlVsCase/",controlcase[i,]$Control," vs ",controlcase[i,]$Case,".png"),width = 512,height = 512)
UpSet(mcontrol[comb_degree(mcontrol)>=2], row_title =controlcase[i,]$Control)%v%UpSet(mcase[comb_degree(mcase)>=2], row_title =controlcase[i,]$Case)
dev.off()